name: Reformat Python Code

on:
  push:
    branches:
      - master

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Black
      run: pip install black

    - name: Reformat Python code
      run: black .

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Reformat code using Black"
        git push
